### ISSUE TITLE
MQTT disconnected - Error: Connection closed

### ISSUE THREAD

**Issue by DaleLJefferson** [csuermann/node-red-contrib-virtual-smart-home#123]
I've followed the instructions, installed and linked the skill and entered the device code but I get this error.

_sensitive stuff replaced with `**`_

```
7 Jan 16:21:42 - [info] [vsh-connection:**] Attempting MQTT connection: a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883 (clientId: **)
7 Jan 16:21:42 - [info] [vsh-connection:**] MQTT subscribe to topics: ["$aws/things/**/shadow/get/accepted","vsh/vsht-**/+/directive","vsh/service","vsh/version/2.13.1/+","vsh/vsht-**/service"]
7 Jan 16:21:42 - [info] [vsh-connection:**] MQTT disconnected
7 Jan 16:21:42 - [info] [vsh-connection:**] MQTT disconnected
Error: Connection closed
    at /data/node_modules/mqtt/lib/client.js:204:29
    at Array.forEach (<anonymous>)
    at flushVolatile (/data/node_modules/mqtt/lib/client.js:202:24)
    at TLSSocket.<anonymous> (/data/node_modules/mqtt/lib/client.js:473:5)
    at TLSSocket.emit (events.js:412:35)
    at net.js:686:12
    at TCP.done (_tls_wrap.js:564:7)
```

I'm running node-red in a docker container (latest version)
```
Node-RED version: v2.1.4
Node.js  version: v14.18.2
node-red-contrib-virtual-smart-home version: 2.13.1
Alexa Country: GB
```

Steps to reproduce:

1. Install and link skill
2. Start node-red container
3. Install node-red-contrib-virtual-smart-home from command palette
4. Add device node and create connection
5. Deploy 

Did I miss a step, please help, this is an amazing project, I would love to use it.

**Comment by DaleLJefferson** [comment]
Update: I added some more logs and got to the bottom of the issue.

```
Error: getaddrinfo ENOTFOUND a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com'
}
```

I jumped into the container and confirmed that I could not ping a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com

So the issue is with my DNS setup not `node-red-contrib-virtual-smart-home` I think the error message was not particularly helpful but that is another issue.
