### ISSUE TITLE
Connection to AWS Topic does not work any longer

### ISSUE THREAD

**Issue by setfire2** [csuermann/node-red-contrib-virtual-smart-home#212]
Since a few days, all my virtual devices stay in state "Initializing..."
I did not change anything on my environment since quite a while. I now discovered the following log entries:

nodered          | 2 Oct 12:21:22 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] Attempting MQTT connection: a1pv0eq8s016ut-ats.iot.eu-west-1.amazonaws.com:8883 (clientId: vsht-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)
nodered          | 2 Oct 12:21:22 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT subscribe to topics: ["$aws/things/vsht-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/shadow/get/accepted","vsh/vsht-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/+/directive","vsh/service","vsh/version/3.0.9/+","vsh/vsht-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/service"]
nodered          | 2 Oct 12:21:22 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT disconnected
nodered          | 2 Oct 12:21:22 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT disconnected
nodered          | Error: Connection closed
nodered          |     at /data/node_modules/mqtt/lib/client.js:206:29
nodered          |     at Array.forEach (<anonymous>)
nodered          |     at flushVolatile (/data/node_modules/mqtt/lib/client.js:204:24)
nodered          |     at TLSSocket.<anonymous> (/data/node_modules/mqtt/lib/client.js:475:5)
nodered          |     at TLSSocket.emit (node:events:539:35)
nodered          |     at node:net:709:12
nodered          |     at TCP.done (node:_tls_wrap:582:7)
nodered          | 2 Oct 12:21:26 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT disconnected
nodered          | 2 Oct 12:21:27 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT disconnected
nodered          | 2 Oct 12:21:31 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT disconnected
nodered          | 2 Oct 12:21:32 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT disconnected
nodered          | 2 Oct 12:21:36 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT disconnected
nodered          | 2 Oct 12:21:38 - [info] [vsh-connection:xxxxxx_yyyyyy@zzz.de] MQTT disconnected

I use Virtual Smarthome 3.0.9

**Comment by setfire2** [comment]
Could it be poosible that the device shadow has been removed from the AWS IoT registry? If so, what could I do about it?

**Comment by setfire2** [comment]
Hello @csuermann,

tried that and it worked. Thanks a lot.

**Comment by setfire2** [comment]
Closed
