### ISSUE TITLE
Newly created devices appear in Device list of connection, but not in Alexa App - Exception is crashing NR

### ISSUE THREAD

**Issue by tt2g89** [csuermann/node-red-contrib-virtual-smart-home#257]
### Bug Description

[error] TypeError: Cannot read properties of undefined (reading 'isActive')
    at ConnectionNode.execCallbackForOne (/data/node_modules/node-red-contrib-virtual-smart-home/connection.js:227:34)
    at ConnectionNode.handleReportState (/data/node_modules/node-red-contrib-virtual-smart-home/connection.js:415:29)
    at MqttClient.<anonymous> (/data/node_modules/node-red-contrib-virtual-smart-home/connection.js:823:24)
    at MqttClient.emit (node:events:513:28)
    at MqttClient.<anonymous> (/data/node_modules/node-red-contrib-virtual-smart-home/MqttClient.js:52:12)
    at MqttClient.emit (node:events:513:28)
    at Array.<anonymous> (/data/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/src/lib/handlers/publish.ts:155:14)
    at Object.MqttClient.options.customHandleAcks (/data/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/src/lib/client.ts:524:14)
    at handlePublish (/data/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/src/lib/handlers/publish.ts:136:12)
    at handle (/data/node_modules/node-red-contrib-virtual-smart-home/node_modules/mqtt/src/lib/handlers/index.ts:29:17)

### To Reproduce

1. Create vsh-thing
2. Deploy Node
3. Wait - unclear, what’s triggering the exception tbh

### Expected behavior

Stable operation of NR, devices appear in Alexa and are operational.

### Virtual-Smart-Home Version

4.4.0

### Node-RED Version

3.1.9

### Node.js Version

16.20.2

### Plan

PRO

### Thing-ID

vsht-f4f5a46e-89b0-45b0-9ffe-e6edd89809da

**Comment by csuermann** [comment]
Hi @tt2g89!

Thank you for reporting this issue!

The stack trace you provided suggests that Alexa sent a ReportState directive to your VSH instance, requesting state information for a virtual device that was locally unknown or not registered. I'm unsure how this could happen, especially since you mentioned that the device doesn't appear in the Alexa app. It might be the result of a temporary connectivity glitch with the Alexa servers.

I will release a fix to prevent Node-RED from crashing when this occurs. However, this fix will not address the root cause of the issue. The update will also include a log message containing the virtual device ID, which I hope will help in troubleshooting this issue further if it persists.

Best regards,
Cornelius
