### ISSUE TITLE
TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by luetty** [csuermann/node-red-contrib-virtual-smart-home#96]
Hi there,

since some days i get errors for all my Temperature Sensors.
I've made many changes in my setup, but i've no idea what's happen here.

Alexa App say's "0,00 C". Removing Device and add them again did not help.

Any hint for me?

`17 Aug 14:43:59 - [error] [vsh-virtual-device:Schlafzimmersensor] TypeError: Cannot read property 'key' of undefined at validateState (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-virtual-smart-home/virtual-device.js:72:43) at VirtualDeviceNode._inputCallback (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-virtual-smart-home/virtual-device.js:111:29) at /opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26 at Object.trigger (/opt/iobroker/node_modules/@node-red/runtime/lib/hooks.js:113:9) at VirtualDeviceNode.Node._emitInput (/opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11) at VirtualDeviceNode.Node.emit (/opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25) at VirtualDeviceNode.Node.receive (/opt/iobroker/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10) at Immediate._onImmediate (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/Flow.js:679:52) at processImmediate (internal/timers.js:464:21)`

thanks in advanced
luetty

**Comment by csuermann** [comment]
Hi @luetty,

What does the context of your "Schlafzimmersensor" look like in Node-RED?

Could you please provide a screenshot similar to below?

![image](https://user-images.githubusercontent.com/10939809/129742602-78cdc57f-674b-40ec-808e-2cfaa2cfd837.png)

**Comment by luetty** [comment]
Hi,

hmmm, it's completly empty. :-(
It seems, that there is a big issue with my setup then.

**Comment by csuermann** [comment]
It will be empty when you restart your flow until the node receives the first Alexa directive or inbound message. Don't forget to click the refresh button, too.

**Comment by luetty** [comment]
The context stay's empty. :-(
![image](https://user-images.githubusercontent.com/89082199/129782796-d0281a88-ea13-4045-b984-8ba459c2e3e2.png)

The errormessages going on, for all my sensors. 
![image](https://user-images.githubusercontent.com/89082199/129782201-b3837c9e-dde3-4ac1-9bb3-10fc61fef2bc.png)

Maybe it depends on my Node.js v14.17.4.
I'm quite new on using iobroker/nodered, but all other is working. Will dig deeper next days.....

**Comment by csuermann** [comment]
Could you please also share the output of your change node / what gets injected into the VSH node?

BTW, which VSH version are you running?

**Comment by luetty** [comment]
that's the output:
![image](https://user-images.githubusercontent.com/89082199/129877924-55f7c252-0b8d-4a5c-8bf7-81c00bd0dc68.png)

It worked up to some days ago.

VSH version is 2.12.1

**Comment by luetty** [comment]
It's completly freaky...

I've setup a debug-installtion, with a backup i know it was working.
It was working! Have made all the steps, i made in production too.... Everything works...

_UP TO: Install all nodes and flows from prod to debug system._ The the error occured again.
After looking deeper, i found the bad guy "node-red-contrib-cul" - i played with. :-(
The install of this node is enough, to produce the issue (i've reinstalled, for testing again).

So, the f...... node is uninstalled, VSH is working perfect now again.

Thanks Cornelius, for your support, a little donation is made.

bR
luetty

**Comment by csuermann** [comment]
Hi @luetty.

That's very weird indeed! Glad to hear you could get everything back to normal.

And many thanks for your donation! 🙇 

Best,
Cornelius
